const API_BASE_URL_DEVELOPMENT = 'https://localhost:7007';
const API_BASE_URL_PRODUCTION = 'https://aspnetcorereacttutorial-aspnetserver.azurewebsites.net';

const ENDPOINTS = {
	REGISTER_USER: 'api/register',
	LOGIN_USER: 'api/login',
	GET_CURRENT_USER: 'api/user',
	LOGOUT_USER: 'api/logout',
};

const development = {
	API_URL_REGISTER_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTER_USER}`,
	API_URL_LOGIN_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN_USER}`,
	API_URL_GET_CURRENT_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_CURRENT_USER}`,
	API_URL_LOGOUT_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGOUT_USER}`,
};

const production = {
	API_URL_REGISTER_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTER_USER}`,
	API_URL_LOGIN_USER: `${API_BASE_URL_PRODUCTION}/${ ENDPOINTS.LOGIN_USER}`,
	API_URL_GET_CURRENT_USER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_CURRENT_USER}`,
	API_URL_LOGOUT_USER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.LOGOUT_USER}`,
};

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;
